<a href="https://colab.research.google.com/github/Xzane-09/SBD/blob/temp/VH_Automation_gcolab_version16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Install the libraries

In [ ]:
# Manual snippet to upgrade any package IF the code fails to update by itself 
#!pip install --upgrade openpyxl

In [3]:
import sys
import subprocess

# List of libraries:
list_lib = ['googletrans==3.1.0a0','python-Levenshtein','fuzzywuzzy','gTTS','unidecode']
upd_lib = ['openpyxl']

for lib in upd_lib:
  subprocess.check_call([sys.executable, '-m', 'pip', 'install','--upgrade', lib])

# implement pip as a subprocess:
for lib in list_lib:
  subprocess.check_call([sys.executable, '-m', 'pip', 'install',lib])

# process output with an API in the subprocess module:
reqs = subprocess.check_output([sys.executable, '-m', 'pip',
'freeze'])

for lib in list_lib:
  installed_packages = [r.decode().split('==')[0] for r in reqs.split()]
  if lib in installed_packages:
    print(lib)

for lib in upd_lib:
  installed_packages = [r.decode().split('==')[0] for r in reqs.split()]
  if lib in installed_packages:
    print(lib)

python-Levenshtein
fuzzywuzzy
gTTS
openpyxl

## Import the libraries

In [4]:
#  ========================================= Basic Imports ====================================================================== 
import pandas as pd
import os
import io
import sys
from datetime import datetime, timedelta
import re
import glob
import numpy as np
import ssl
import warnings
from google.colab import drive
from google.colab import files
import chardet
import unicodedata
from unidecode import unidecode

warnings.filterwarnings("ignore")

#========================================= Processing Bar notification ====================================================
from googletrans  import Translator
translator = Translator(service_urls = ['translate.googleapis.com']) 

#========================================= Processing Bar notification ====================================================
from tqdm.notebook import tqdm
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

#========================================= Model Imports ==================================================================
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn import preprocessing
from sklearn.preprocessing import RobustScaler,MinMaxScaler,MaxAbsScaler

#========================================= For sound notification =========================================================
from gtts import gTTS

In [5]:
process_start_time =  datetime.now()
scaling = MaxAbsScaler
tfidf_transformer = TfidfTransformer()
count_vect = CountVectorizer()
SGD = SGDClassifier(loss='hinge', penalty='l2', max_iter=1000, learning_rate='constant',eta0 = 0.1)

### All definations

In [6]:
def reading_master_files():
  uploads = files.upload()
  tot_files = len(uploads.keys())

  if tot_files>1:
    frame=[]
    total = 0
    for fn in uploads.keys():
        file = pd.read_excel(io.BytesIO(uploads[fn]))
        rep_col = 'Predicted Names/ Model Cleansed'
        rep_col_dict = {'Predicted Names/ Model Cleansed':'New Supplier'} # new supplier as manually harmonized names/previously harmonized/model cleansed
        for col in file.columns:
            if col == rep_col:
                file.rename(columns = rep_col_dict, inplace = True)
        file = file[['DataSource','Vendor number','Vendor name', 'New Supplier']]
        dimen = file.shape
        nr = dimen[0]
        nc = dimen[1]
        total=total+nr
        file.reset_index(inplace=True,drop=True)
        frame.append(file)
    consolidated_df = pd.concat(frame,sort=False)
    consolidated_df.reset_index(inplace=True,drop=True)
    raw_df = consolidated_df.copy()

    for fn in uploads.keys():
      with open(fn, 'rb') as rawdata:
        result = chardet.detect(rawdata.read(18))
        print(f'Filename: {fn}\nInfo: {result} \n')

  else:
    filename = uploads.keys()
    filename = str(filename)
    filename = re.findall(r"\'.*?\'", filename)[0]
    filename = re.sub("'","",filename)
    with open(filename, 'rb') as rawdata:
      result = chardet.detect(rawdata.read(18))
      print(f'Filename: {filename}\nInfo: {result} \n')
    file = pd.read_excel(io.BytesIO(uploads[filename]))
    dimen = file.shape
    nr = dimen[0]
    nc = dimen[1]
    total=nr
    file = file[['DataSource','Vendor number','Vendor name', 'New Supplier']]
    raw_df = file.copy()

  return(raw_df,total,tot_files)


def vendor_harmonized_stop_word(name):
    s = " ".join([i for i in re.split(r' ', name) if not i in vendor_harmonized_stopwords]).strip()
    return s


def trim_spaces(name):
#    s = " ".join([i for i in re.split(r' ', name)]).strip()
#    return s
    s = " ".join(name.split()).strip()
    return s


def new_old_match_stopword(name):
    s = "".join([i for i in re.split(r' ', name) if not i in new_old_match_stopwords]).strip()
    return s


def Clean_Vendor_Name_stopword(name):
    s = " ".join([i for i in re.split(r' ', name) if not i in new_old_match_stopwords]).strip()
    return s

    

def rep(name): # same function name has been used twice recheck the dependency and change accordingly
    return(name.replace("`","",1))


def norm_vendorNames(vname): # same function name has been used twice recheck the dependency and change accordingly
  normalized = unicodedata.normalize('NFD', vname)
  norm_vname = u"".join([c for c in normalized if not unicodedata.combining(c)])
  return(norm_vname)


def decode_vnames(vname):
  return(unidecode(vname))


def data_clean(file):
    proc_df = file
    proc_df['Vendor name'] = proc_df['Vendor name'].apply(lambda x: str(x)) # added this line to remove suhong type of city names from vendor names. Do the same with other defs 
    proc_df= final_output_sup_name_Cleaning(proc_df,'Vendor name')  # added function to remove city names
    proc_df['Vendor name'] = proc_df['Vendor name'].apply(decode_vnames)
    proc_df['Clean_Vendor_Name'] = proc_df['Vendor name'].apply(lambda x: str(x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: x.replace('DO NOT USE', ''))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(decode_vnames)
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df= final_output_sup_name_Cleaning(proc_df,'Clean_Vendor_Name') # added function to remove city names
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub('[#,.,/,]', ' ',x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: x.lower())
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(vendor_harmonized_stop_word)
    
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(Clean_Vendor_Name_stopword) # added this new line
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(trim_spaces) # added this new line

    proc_df['New Supplier'] = proc_df['New Supplier'].apply(decode_vnames)
    
    return proc_df


def data_clean_initials(file):
    proc_df = file
    proc_df['Vendor_name_Initials'] = proc_df['Clean_Vendor_Name'].apply(lambda x: str(x))
    #proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    #print()
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: x[0])
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: re.sub('[@,?,#,(,),*,+,.,-,_,`,~]', ' ',x))
    #proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(vendor_harmonized_stop_word)
    
    proc_df['New_Supplier'] = proc_df['New Supplier'].apply(lambda x: str(x))
    proc_df['New_Supplier'] = proc_df['New Supplier'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub('[@?#()*_~]', '',x))
    proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: x.lower())
    proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub('"', '',x))
    proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub("'", '',x))
    #proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub(r'-', ' ', x))
    #proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub(r'[^\s]', '', x))
    proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(vendor_harmonized_stop_word) # why we are removing from new_supplier
    return proc_df


def input_df_data_clean(file):
    proc_df = file
    
    # Below steps are the cleaning for vendors:
    proc_df['Vendor name'] = proc_df['Vendor name'].apply(lambda x: str(x)) # added this line to remove suhong type of city names from vendor names. Do the same with other defs 
    proc_df= final_output_sup_name_Cleaning(proc_df,'Vendor name')
    proc_df['Vendor name'] = proc_df['Vendor name'].apply(decode_vnames)
    proc_df['Clean_Vendor_Name'] = proc_df['Vendor name'].apply(lambda x: str(x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(decode_vnames)
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub('[#,.,/,]', ' ',x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(vendor_harmonized_stop_word)
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df= final_output_sup_name_Cleaning(proc_df,'Clean_Vendor_Name')
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: x.lower())
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(Clean_Vendor_Name_stopword)# added this line extra
    proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(trim_spaces)
    proc_df.replace("", np.nan, inplace=True) #try with commenting this line and below too to check the difference
    proc_df.dropna(subset = ["Clean_Vendor_Name"],inplace=True)
    return proc_df


def crisp_vendor_name(file):
    proc_df = file
    proc_df['crisp_vendor_name'] = proc_df['Clean_Vendor_Name'].apply(lambda x: str(x))
    #proc_df['crisp_vendor_name'] = proc_df['crisp_vendor_name'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    #proc_df['crisp_vendor_name'] = proc_df['crisp_vendor_name'].apply(lambda x: re.sub(' ', '',x))
    proc_df['crisp_vendor_name'] = proc_df['crisp_vendor_name'].apply(new_old_match_stopword)
    return proc_df


   
def input_df_data_ini(file):
    proc_df = file
    proc_df['Vendor_name_Initials'] = proc_df['Clean_Vendor_Name'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: x[0])
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df['Vendor_name_Initials'] = proc_df['Vendor_name_Initials'].apply(lambda x: re.sub('[@,?,#,(,),*,+,.,-,_,`,~]', ' ',x))
    #proc_df['Clean_Vendor_Name'] = proc_df['Clean_Vendor_Name'].apply(vendor_stop_word)
    return proc_df


def inp_CleaningChamber(file):
    proc_df = file
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor name'].apply(lambda x: str(x))
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x))
    proc_df= final_output_sup_name_Cleaning(proc_df,'Vendor_Name_cleansed') # Added function to remove city names
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: re.sub('[@?#()*_~/]', ' ',x))
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: x.lower())
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: re.sub('"', '',x))
    #proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: re.sub("'", '',x))
    #proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(lambda x: re.sub(r'-', ' ', x))
    #proc_df['New_Supplier'] = proc_df['New_Supplier'].apply(lambda x: re.sub(r'[^\s]', '', x))
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(vendor_harmonized_stop_word)
    proc_df['Vendor_Name_cleansed'] = proc_df['Vendor_Name_cleansed'].apply(trim_spaces)
    return proc_df


def bucket_df(df,initials_lists):
    bucket_df_list =[]
    grp_df = df.groupby(df.Vendor_name_Initials)
    for char in initials_lists:
        bucket_df_list.append(grp_df.get_group(char))
    return(bucket_df_list)



def time_util(pred_time):
    # total_seconds = pred_time.seconds
    seconds = int(pred_time.total_seconds())
    secs_in_a_min = 60
    minutes, seconds = divmod(seconds, secs_in_a_min)

    time_fmt = f"{minutes:02d} {seconds:02d} secs"

    if minutes > 0:
        suffix = 's' if minutes > 1 else ""
        return f'{minutes} min{suffix} & {seconds} secs'

    return time_fmt


def sgd_clf(i):
    Tot_St_Time = datetime.now()
    grp_number = np.unique(grp_clean_main_df_list[i]['Vendor_name_Initials'])[0]
    Train_X,Test_X,Train_Y,Test_Y = train_test_split(grp_clean_main_df_list[i]['Clean_Vendor_Name'],grp_clean_main_df_list[i]['New_Supplier'],test_size=0.00001, random_state=0)
    X_train_counts = count_vect.fit_transform(Train_X)
    X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
    sgd_clf=SGD.fit(X_train_tfidf,Train_Y)
    Tot_End_Time = datetime.now()
    Tot_time_taken = Tot_End_Time - Tot_St_Time
    return(time_util(Tot_time_taken),grp_number,sgd_clf)

def Match_wordLength(i):
    if (merged_final['Model_pred_Supplier'][i] == merged_final['Prev_Predicted_Supplier'][i]):
        merged_final['Match_word_len'].loc[i] = 'Same Length'
    else:
        merged_final['Match_word_len'].loc[i] = 'Different Length'
    return(merged_final['Match_word_len'])

def rep(name):
    return(name.replace("-","",1))


def trans_name(name):
  srch = re.search("([^\x00-\x7F])+",name)==None
  if srch:
    return(name)
  else:
    return(translator.translate(str(name), dest = 'en').text)




punc = '''!(-[](){};`:)/'"\,<>.?@#$%^*+_~'''  
invalid_punc = ['*','#']
def rem_first_char_punc(name):  # check this whether it is implemented or not
    count = 0
    frame=[]
    for i in range(len(name)):
        if name[i] in punc:
            frame.append(name[i])
            #print(name[i])
            count = count+1
    unq_name_punc = np.unique(frame)
    unq_name_punc = unq_name_punc.tolist()
    for i in range(len(invalid_punc)):
        if invalid_punc[i] in unq_name_punc:
            name=name.replace(invalid_punc[i],'')

    limit = 0
    for i in range(len(name)):
        if name[i] not in punc:
            #print(name[i])
            break
        else:
            #print(name[i])
            limit = limit + 1
            #break
    upper_limit = limit  
    #print(upper_limit) 
    for i in range(upper_limit):
        if name[0] in punc:
            #print(f'the found punctuation is "{name[0]}"')
            name=name.replace(name[0],'',1)
    return(name)


def ds_cleansing(name):
  #print(type(name))
  if type(name) is np.str:
    punc_list = [',','.']
    for c in name:
        if c not in punc_list:
            pass
        else:
            split_string = re.split(f"[{c}]", name)
            name = split_string[len(split_string)-1].strip()
  else:
    pass
  return(name)


def rep_harmonized_sup_name(name):
  #name = str(name)
  for i in re.split(r' ', name):
    if str.upper(i) in supplier_stopwords:
      idx = name.index(i)
      if idx == 0:
        return(name.replace(i,"",1))
    else:
      return(name)


def final_output_sup_name_Cleaning(file,column_name):
    proc_df = file.copy()
    proc_df[column_name]= proc_df[column_name].apply(rep_harmonized_sup_name)
    return(proc_df)



def vendorFlag_wo_VN(i):
    #if (input_df['Clean_Vendor_Name'].iloc[i] in clean_main_df['Clean_Vendor_Name']):
    if (input_df['Clean_Vendor_Name'][i] in clean_main_df['Clean_Vendor_Name'].values)|(input_df['crisp_vendor_name'][i] in clean_main_df['crisp_vendor_name'].values):
      input_df['Vendor_Flag'].iloc[i] = 'Old'
    #elif (input_df['crisp_Vendor_Name'][i] in clean_main_df['crisp_Vendor_Name'].values):
    #  input_df['Vendor_Flag'].iloc[i] = 'Old'
    else:
      input_df['Vendor_Flag'].iloc[i] = 'New'
    return(input_df)



def vendorFlag(i):
    #if (input_df['Clean_Vendor_Name'].iloc[i] in clean_main_df['Clean_Vendor_Name']):
    if ((input_df['Clean_Vendor_Name'][i] in clean_main_df['Clean_Vendor_Name'].values) and\
        (input_df['DataSource'][i] in clean_main_df['DataSource'].values) and\
        (input_df['Vendor number'][i] in clean_main_df['Vendor number'].values))\
    or ((input_df['crisp_vendor_name'][i] in clean_main_df['crisp_vendor_name'].values) and (input_df['DataSource'][i] in clean_main_df['DataSource'].values) and (input_df['Vendor number'][i] in clean_main_df['Vendor number'].values)):
      #if(input_df['DataSource'][i] in clean_df['DataSource'].values) and (input_df['Vendor number'][i] in clean_df['Vendor number'].values):
      input_df['Vendor_Flag'].iloc[i] = 'Old'
    #elif (input_df['crisp_Vendor_Name'][i] in clean_main_df['crisp_Vendor_Name'].values):
    #  input_df['Vendor_Flag'].iloc[i] = 'Old'
    else:
      input_df['Vendor_Flag'].iloc[i] = 'New'
    return(input_df)


def lingual_check(file):
  proc_df = file
  for n in proc_df[proc_df.columns[0]]:
#  #print(n)
    srch = re.search("([^\x00-\x7F])+",n)==None
    if srch:
      print('no match')
      break
    else:
      print('There are other format of languages present in the file')
      break



# Drop unwanted column names by giving the list of column names in  a list
def drop_cols_df(col_list,dataframe):
  for col in dataframe.columns:
    if col not in col_list:
      dataframe.drop(columns=col,axis=1,inplace=True)
                

# For checking whether there are any duplicates or not

def dup_count(check_dataframe):
  dup_count= check_dataframe[check_dataframe.duplicated()==True].count().unique()[0]
  dup_dataframe = check_dataframe[check_dataframe.duplicated()==True]

  return(dup_count,dup_dataframe)


def check_dup_count(check_df):
  count_dup, dup_df = dup_count(check_df)
  #globals()['count_duplicates'] = count_dup
  if count_dup > 1 and count_dup < 8:
      print(dup_df)
  else:
    print('Total Duplicates in Dataset: ',count_dup)

  return(count_dup)


# To count foreign names
def count_foreign(df,col_name):
  count = 0
  for n in df[col_name]:
    srch = re.search("([^\x00-\x7F])+",n)==None
    if srch:
      pass
    else:
      count = count + 1
  #print(f'Other name formats in "new supplier" column : {count}')
  return(count)

In [7]:
master_file,length,no_of_files = reading_master_files()

Saving Master data.xlsx to Master data.xlsx
Filename: Master data.xlsx
Info: {'encoding': None, 'confidence': 0.0, 'language': None}

In [8]:
print('User uploaded master file with {length} records'.format(length=length))

User uploaded master file with 228989 records

In [9]:
# Master file
master_file.head(4)

               DataSource  ...            New Supplier
0  68. 3rd Party Security  ...       LEEUWENBURGH MARK
1             10. SAP C11  ...  ANTIESTATICA DE MEXICO
2             15. SAP SP1  ...         LE BLEU PHILLIP
3             12. SAP SEP  ...               MICROSOFT

[4 rows x 4 columns]

In [10]:
raw_df = master_file.copy()
raw_df['Vendor name'].drop_duplicates(inplace=True)
raw_df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228989 entries, 0 to 228988
Columns: 4 entries, DataSource to New Supplier
dtypes: object(4)
memory usage: 7.0+ MB

#### Dropping the null rows:

In [11]:
# Use raw_df to get vendor number and DataSource at the end. So copy only Vendor name and new supplier to df
df = raw_df.copy()
df.dropna(inplace=True)  # Here is first drop NA
df['Vendor name'].drop_duplicates(inplace=True) # Dropping duplicates Distinguish between NA and duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 228922 entries, 0 to 228921
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DataSource     228922 non-null  object
 1   Vendor number  228922 non-null  object
 2   Vendor name    228922 non-null  object
 3   New Supplier   228922 non-null  object
dtypes: object(4)
memory usage: 8.7+ MB

In [12]:
#df[df['Vendor name'].str.contains('Suzhou')]

In [13]:
after_drop_na_1 = df.shape[0]

In [14]:
no_of_null_records1= length - after_drop_na_1
no_of_null_records1

67

In [15]:
df['DataSource']=df['DataSource'].apply(ds_cleansing)

In [16]:
df.sample(2)

       DataSource Vendor number             Vendor name            New Supplier
102906    JDE CAM        176750  JE COMPLIANCE SERVICES  JE COMPLIANCE SERVICES
172069    SAP SEP        111657       SARL BREMAUD EPUR                 BREMAUD

### Defined set of stopwords:

In [17]:
vendor_harmonized_stopwords = ['me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
                "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself',
                'yourselves', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers',
                'herself', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', #'it',
                'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these',
                'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has',
                'had', 'having', 'do', 'does', 'did', 'doing','an', #'the', 'and',
                'but','if', 'or', 'because', 'until', 'while', 'at', 'by', 'with', #'for','of', 
                'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',
                'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over',
                'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where',
                'why', 'how', 'any', 'both', 'each', 'few', 'more', 'most', 'other',
                'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too',
                'very', 'can', 'just', 'don', "don't", 'should', "should've",
                'now', 'll', 're', 've', 'ain', 'aren', "aren't", 'couldn',
                "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn',
                "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't",
                'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't",
                'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't",'dr','use' #'co',
                #'company', 'ltd', 'co ltd', 'company ltd', 'inc', 'llc', 'lp', 'corp', 'corporation',
                ]#'a','d', 's','i','m', 't', 'o', 'y','he','all','will', 'as'

In [18]:
new_old_match_stopwords = ['co', 'company', 'ltd', 'co ltd', 'company ltd', 'inc', 'llc', 'lp', 'corp', 'corporation','ltl','ftl']

In [19]:
supplier_stopwords = ['ZHEJIANG','ZHANGZHOU','ZHONGSHAN','QINGDAO','QIDONG','SUZHOU'] # all words should be in upper case

In [20]:
df['Vendor name'] = df['Vendor name'].apply(rem_first_char_punc)  # try to implement for input data also IF NOT
df['New Supplier'] = df['New Supplier'].apply(rem_first_char_punc)
df['Vendor name'].drop_duplicates(inplace=True)  #

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 228922 entries, 0 to 228921
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DataSource     228922 non-null  object
 1   Vendor number  228922 non-null  object
 2   Vendor name    228922 non-null  object
 3   New Supplier   228922 non-null  object
dtypes: object(4)
memory usage: 8.7+ MB

In [22]:
sh_df = df.shape[0]
sh_df

228922

In [23]:
# Below code is to verify whether are there any names apart from english lingual
count = 0
for n in df['New Supplier']:
  srch = re.search("([^\x00-\x7F])+",n)==None
  if srch:
    pass
  else:
    count = count + 1
print(f'Foreign name formats in "new supplier" column : {count}')



count = 0
for n in df['Vendor name']:
  srch = re.search("([^\x00-\x7F])+",n)==None
  if srch:
    pass
  else:
    count = count + 1
print(f'Foreign name formats in "Vendor name" column : {count}')

Foreign name formats in "new supplier" column : 3535
Foreign name formats in "Vendor name" column : 7461

In [24]:
df.head(2)

           DataSource  ...            New Supplier
0  3rd Party Security  ...       LEEUWENBURGH MARK
1             SAP C11  ...  ANTIESTATICA DE MEXICO

[2 rows x 4 columns]

In [25]:
## This snippet will print the name of the Column IF there are any NULL records in that Column
if (df.isna().sum().unique()[0] != 0):
  for i in df.columns:
    if df[i].isna().sum() !=0:
      print(i + '\n')
    else:
      pass
else:
  pass

In [26]:
clean_df = data_clean(df)
clean_df['Clean_Vendor_Name'] = clean_df['Clean_Vendor_Name'].apply(trim_spaces)
clean_df.replace("", np.nan, inplace=True)
clean_df.dropna(subset = ["Clean_Vendor_Name","Vendor name"],inplace=True)
clean_df = data_clean_initials(clean_df)
clean_df = crisp_vendor_name(clean_df)

clean_df['DataSource'] = clean_df['DataSource'].apply(lambda x: str(x))
clean_df['Vendor number'] = clean_df['Vendor number'].apply(lambda x: str(x))
clean_df['DataSource'] = clean_df['DataSource'].apply(trim_spaces)
clean_df['Vendor number'] = clean_df['Vendor number'].apply(trim_spaces)


clean_df= clean_df[['DataSource', 'Vendor number', 'Vendor name','Clean_Vendor_Name','crisp_vendor_name','New Supplier','New_Supplier','Vendor_name_Initials']]
clean_df.reset_index(inplace=True,drop=True)

In [27]:
clean_df.sample(2)

       DataSource Vendor number  ...            New_Supplier Vendor_name_Initials
223948    SAP E03        173348  ...  zenith automazione srl                    z
177392      Ariba  20013803-A10  ...        future high-tech                    s

[2 rows x 8 columns]

In [28]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228886 entries, 0 to 228885
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   DataSource            228886 non-null  object
 1   Vendor number         228886 non-null  object
 2   Vendor name           228886 non-null  object
 3   Clean_Vendor_Name     228886 non-null  object
 4   crisp_vendor_name     228886 non-null  object
 5   New Supplier          228886 non-null  object
 6   New_Supplier          228886 non-null  object
 7   Vendor_name_Initials  228886 non-null  object
dtypes: object(8)
memory usage: 14.0+ MB

In [29]:
sh_clean_df = clean_df.shape[0]

In [30]:
no_of_null_records2 = sh_df - clean_df.shape[0]
no_of_null_records2

36

In [31]:
clean_df.replace("", np.nan, inplace=True)
clean_df.dropna(subset = ["Clean_Vendor_Name"],inplace=True)
clean_df.dropna(subset = ['New_Supplier'],inplace=True)
clean_ini_list = clean_df['Vendor_name_Initials'].apply(lambda x: re.sub("([^\x00-\x7F])+"," ",x)).unique()
clean_ini_list = np.sort(clean_ini_list)
clean_ini_list = list(filter(str.strip, clean_ini_list))

In [32]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 228884 entries, 0 to 228885
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   DataSource            228884 non-null  object
 1   Vendor number         228884 non-null  object
 2   Vendor name           228884 non-null  object
 3   Clean_Vendor_Name     228884 non-null  object
 4   crisp_vendor_name     228884 non-null  object
 5   New Supplier          228884 non-null  object
 6   New_Supplier          228884 non-null  object
 7   Vendor_name_Initials  228884 non-null  object
dtypes: object(8)
memory usage: 15.7+ MB

In [33]:
no_of_null_records3 = sh_clean_df - clean_df.shape[0]
no_of_null_records3

2

In [34]:
# Filtering the Clean data from noisy data with Non-English Vendor Names
clean_df['noise_flag'] = clean_df['Vendor name'].apply(lambda x: True if (re.findall("([^\x00-\x7F])+",x)) else False)
clean_main_df = clean_df[clean_df['noise_flag'] == False]
clean_main_df.reset_index(inplace=True,drop=True)

In [35]:
clean_main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228884 entries, 0 to 228883
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   DataSource            228884 non-null  object
 1   Vendor number         228884 non-null  object
 2   Vendor name           228884 non-null  object
 3   Clean_Vendor_Name     228884 non-null  object
 4   crisp_vendor_name     228884 non-null  object
 5   New Supplier          228884 non-null  object
 6   New_Supplier          228884 non-null  object
 7   Vendor_name_Initials  228884 non-null  object
 8   noise_flag            228884 non-null  bool
dtypes: bool(1), object(8)
memory usage: 14.2+ MB

In [36]:
sh_clean_main_df = clean_main_df.shape[0]
#sh_clean_main_df

In [37]:
no_of_noise_flags = clean_df.shape[0] - clean_main_df.shape[0]
no_of_noise_flags

0

In [38]:
clean_main_df[clean_main_df['Vendor number'] == '40002318']

                DataSource Vendor number  ... Vendor_name_Initials noise_flag
162291  3rd Party Security      40002318  ...                    t      False
162292  3rd Party Security      40002318  ...                    t      False

[2 rows x 9 columns]

In [39]:
clean_main_df.tail()

       DataSource Vendor number  ... Vendor_name_Initials noise_flag
228879    SAP C11      30091481  ...                    h      False
228880    SAP C11      30103393  ...                    h      False
228881    SAP C11      30103393  ...                    h      False
228882    SAP E03        170391  ...                    l      False
228883    SAP E03        170391  ...                    l      False

[5 rows x 9 columns]

In [40]:
tot_no_of_clean_records = clean_main_df.shape[0]
#tot_no_of_clean_records

In [41]:
rest_main_df = clean_df[clean_df['noise_flag'] == True]
rest_main_df.reset_index(inplace=True,drop=True)

In [42]:
rest_main_df.shape[0] # Duplicates may be present. So check the count of 'no_of_unique_dirty_records'

0

In [43]:
rest_main_df.head(2)

Empty DataFrame
Columns: [DataSource, Vendor number, Vendor name, Clean_Vendor_Name, crisp_vendor_name, New Supplier, New_Supplier, Vendor_name_Initials, noise_flag]
Index: []

In [44]:
rest_main_df.drop_duplicates(subset=['Vendor name'], inplace=True)

Empty DataFrame
Columns: [DataSource, Vendor number, Vendor name, Clean_Vendor_Name, crisp_vendor_name, New Supplier, New_Supplier, Vendor_name_Initials, noise_flag]
Index: []

In [45]:
no_of_unique_dirty_records = rest_main_df.shape[0] # Unique no of dirty records
no_of_unique_dirty_records

0

In [46]:
rest_main_df = rest_main_df[['DataSource', 'Vendor number','Vendor name', 'New Supplier']]

In [47]:
#This percentage is calculated to know how much irregular unique records are present. Need to check this evertime.
# This percentage is good to be in range of 5~8%
per_irr = format((rest_main_df.shape[0]/clean_df.shape[0])*100, ".3f") # show this to Christian.
if float(per_irr)<8:
    print(f'The percentage of irregular records is below the threshold value (5~8%):  {per_irr}'+'%')
else:
    print(f'The percentage of irregular records is above the threshold value (5~8%):  {per_irr}'+'%')

The percentage of irregular records is below the threshold value (5~8%):  0.000%

## Extracting Bad/uncleaned Master Data:

In [48]:
rest_main_df.to_excel('Uncleaned_MainData.xlsx',index=False,encoding='utf8')
files.download('Uncleaned_MainData.xlsx')

## Bucketing the master data/ Group the initials

In [49]:
grp_clean_main_df_list = bucket_df(clean_main_df,clean_ini_list)

In [50]:
grp_clean_main_df_list[13]

           DataSource Vendor number  ... Vendor_name_Initials noise_flag
51      Epicor Avante          1789  ...                    d      False
52            SAP E03        167221  ...                    d      False
53              INBUS  CA6282-KOREA  ...                    d      False
250            QAD PE      D5237416  ...                    d      False
251            QAD PE      S1111955  ...                    d      False
...               ...           ...  ...                  ...        ...
228722        SAP C11      30108513  ...                    d      False
228792        SAP C11      30088660  ...                    d      False
228862        SAP C11      30057868  ...                    d      False
228863        SAP C11      30057868  ...                    d      False
228864        SAP C11      30057868  ...                    d      False

[10555 rows x 9 columns]

# Input file:

In [51]:
input_uploads = files.upload()

Saving Percentage of Spend with all columns.xlsx to Percentage of Spend with all columns.xlsx

In [52]:
# Input file extension validation

name_ext_frame = []
for fn in input_uploads.keys():
  name, extension = os.path.splitext(fn)
  ext = extension.replace('.','')
  name_ext_frame.append([name,ext])


for i in range(len(name_ext_frame)):
    if str.lower(name_ext_frame[i][1]) != 'xlsx':
      print('Alert Info:: file with other extension apart from "XLSX":', name_ext_frame[i])
    else:
      print('Info::'+'\n'+
            'File extension:: XLSX')

Info::
File extension:: XLSX

In [53]:
tot_files = len(input_uploads.keys())
tot_files

1

In [54]:
if tot_files >1:
    inp_frame=[]
    #total = 0
    inp_total = 0
    for fn in input_uploads.keys():
        print(f'Filename: {fn}')
        file = pd.read_excel(io.BytesIO(input_uploads[fn]))
        dimen = file.shape
        nr = dimen[0]
        nc = dimen[1]
        inp_total=inp_total+nr
        print(f'\nNo. of Rows: {nr}\nNo. of cols: {nc}\n')
        print('\n')
        
        file.reset_index(inplace=True,drop=True)
        inp_frame.append(file)
    cons_inp_df = pd.concat(inp_frame,sort=False)
    print(f'total: {inp_total}\n___________________________________________________________________________________________')
    input_raw_df = cons_inp_df.copy()
    refined_inp_col_names = (input_raw_df.columns.to_series(index=range(len(input_raw_df.columns))).apply(lambda x : trim_spaces(x))).to_list()
    input_raw_df.columns=refined_inp_col_names
else:
    print('Else- section')
    inp_total = 0
    print(f'Filename: {fn}')
    file = pd.read_excel(io.BytesIO(input_uploads[fn]))
    file = file.sample(500)  #kept this line for testing purpose, keep the number as per your testing, Random records
    dimen = file.shape
    nr = dimen[0]
    nc = dimen[1]
    
    inp_total=inp_total+nr
    print(f'\nNo. of Rows: {nr}\nNo. of cols: {nc}\n')
    print('\n')
    print(f'total: {inp_total}\n_________________________________________________________________________________________________')
    input_raw_df = file.copy()
    refined_inp_col_names = (input_raw_df.columns.to_series(index=range(len(input_raw_df.columns))).apply(lambda x : trim_spaces(str(x)))).to_list()
    input_raw_df.columns=refined_inp_col_names

Else- section
Filename: Percentage of Spend with all columns.xlsx

No. of Rows: 500
No. of cols: 14



total: 500
_________________________________________________________________________________________________

In [55]:
no_of_raw_inp_records = inp_total
no_of_raw_inp_records

500

In [56]:
# give the input column names that is required and need to drop the rest 
acp_inp_col_names = ['DataSource','Vendor number','Vendor name','Spend (USD)','Segment','Primary Category']

In [57]:
drop_cols_df(acp_inp_col_names,input_raw_df)

In [58]:
input_raw_df.columns

Index(['DataSource', 'Vendor number', 'Vendor name', 'Spend (USD)', 'Segment',
       'Primary Category'],
      dtype='object')

In [59]:
#input_raw_df[input_raw_df.duplicated()==True].count()#.unique()[0]
input_raw_df.reset_index(inplace=True,drop=True)

In [60]:
count_dup = check_dup_count(input_raw_df)

Total Duplicates in Dataset:  0

In [61]:
input_raw_df_null_records = input_raw_df[input_raw_df['Vendor name'].isnull()]

In [62]:
input_raw_df_null_records

Empty DataFrame
Columns: [DataSource, Vendor number, Vendor name, Spend (USD), Segment, Primary Category]
Index: []

In [63]:
input_raw_df_null_records.to_excel('input file null records.xlsx',index=False,encoding='utf8')
files.download('input file null records.xlsx')

In [64]:
# Drop Na's if any:
count_na_inp_raw_df = input_raw_df.isnull().sum().max()
print("Raw Dataframe NA Count: ",count_na_inp_raw_df)
if count_na_inp_raw_df>0:
  na_dict  = input_raw_df.isnull().sum().to_dict()#:  #.max()>0
  for k,v in na_dict.items():
    if v>0:
      if (v == input_raw_df.isnull().sum().max()) and (k in ['DataSource',	'Vendor number',	'Vendor name']):
        print("The column with maximum NA counts: ",k)
        print("Info:   Dropping the NAs from the Dataframe:::::::::::")
        input_raw_df.dropna(inplace=True)
        input_raw_df.reset_index(inplace=True,drop=True)


# Drop duplicates if any:
if count_dup>0:
  input_raw_df.drop_duplicates(inplace=True)


# Now reset the index
input_raw_df.reset_index(inplace=True,drop=True)

Raw Dataframe NA Count:  0

In [65]:
check_dup_count(input_raw_df)

Total Duplicates in Dataset:  0

0

In [66]:
input_raw_df.sort_index(inplace=True)
input_raw_df.reset_index(drop=True, inplace=True)

In [67]:
input_raw_df.shape

(500, 6)

In [68]:
no_of_null_inp_records1 = inp_total - input_raw_df.shape[0]
no_of_null_inp_records1

0

In [69]:
foreign_count = count_foreign(input_raw_df,'Vendor name')
print(f'Foreign name/names count: {foreign_count}') # if foreign counts greater than 1 then fetch the records by implementing noise flag

Foreign name/names count: 3

In [70]:
if foreign_count>0:
  #input_raw_df['Vendor name'] = input_raw_df['Vendor name'].apply(trans_name)
  input_raw_df['noise_flag'] = input_raw_df['Vendor name'].apply(lambda x: True if (re.findall("([^\x00-\x7F])+",x)) else False)
  foreign_inp_df = input_raw_df[input_raw_df['noise_flag'] == True]
  foreign_inp_df.to_excel('foreign input data.xlsx',index=False,encoding='utf8')
  files.download('foreign input data.xlsx')
  
  # Also filter non foreign data from input data
  input_raw_df = input_raw_df[input_raw_df['noise_flag'] == False]
  input_raw_df.drop(columns=['noise_flag'],axis = 1, inplace=True)
  input_raw_df.reset_index(drop=True,inplace=True)

In [71]:
input_raw_df.shape[0]

497

In [72]:
input_raw_df.head(2)

    DataSource Vendor number  ...     Segment     Primary Category
0    11. Ariba    1031587-A9  ...   CORPORATE  General Procurement
1  70. JDE CAM        176488  ...  INDUSTRIAL       Transportation

[2 rows x 6 columns]

In [73]:
lingual_check(input_raw_df)

no match

In [74]:
inp_match_df = input_raw_df.copy()

In [76]:
inp_match_df.shape

(497, 6)

In [77]:
lingual_check(inp_match_df)

no match

In [78]:
inp_match_df.head(2)

    DataSource Vendor number  ...     Segment     Primary Category
0    11. Ariba    1031587-A9  ...   CORPORATE  General Procurement
1  70. JDE CAM        176488  ...  INDUSTRIAL       Transportation

[2 rows x 6 columns]

In [79]:
# Input data cleaning

input_df = input_df_data_clean(input_raw_df)
input_df = input_df_data_ini(input_df)
input_df = crisp_vendor_name(input_df)

# this DS cleaning is optional
for col in input_df.columns:
  if col == 'DataSource':
    input_df['DataSource']=input_df['DataSource'].apply(ds_cleansing)

In [80]:
records_removed_after_data_cleaning = inp_match_df.shape[0] - input_df.shape[0]
records_removed_after_data_cleaning

0

In [81]:
input_df.columns

Index(['DataSource', 'Vendor number', 'Vendor name', 'Spend (USD)', 'Segment',
       'Primary Category', 'Clean_Vendor_Name', 'Vendor_name_Initials',
       'crisp_vendor_name'],
      dtype='object')

In [82]:
for col in input_df.columns:
  if col in ['DataSource','Vendor number']:
    input_df['DataSource'] = input_df['DataSource'].apply(lambda x: str(x))
    input_df['Vendor number'] = input_df['Vendor number'].apply(lambda x: str(x))
    input_df['DataSource'] = input_df['DataSource'].apply(trim_spaces)
    input_df['Vendor number'] = input_df['Vendor number'].apply(trim_spaces)
  else:
    pass

In [83]:
lingual_check(input_df)

no match

In [84]:
input_df.shape[0]

497

In [85]:
input_df.reset_index(inplace=True,drop=True)

In [86]:
input_df

             DataSource  ...       crisp_vendor_name
0                 Ariba  ...                 gartner
1               JDE CAM  ...          federalexpress
2    3rd Party Security  ...  hamosadlebetichutgahut
3                   IFS  ...                idescooy
4          SAP SHP (S4)  ...                euracier
..                  ...  ...                     ...
492        SAP SHP (S4)  ...                   ast25
493        Syteline IES  ...         lincolnelectric
494             SAP P10  ...            federalalarm
495        SAP SHP (S4)  ...                   opsat
496        SAP SHP (S4)  ...    ticketrestportugalsa

[497 rows x 9 columns]

In [87]:
count_col = 0
for col in input_df.columns:
  if col in acp_inp_col_names:
    count_col = count_col +1
print(count_col)
input_df['Vendor_Flag']=np.nan
if count_col==1:
  for i in tqdm(range(len(input_df))):
    vendorFlag_wo_VN(i)
  input_df['DataSource']=np.nan
  input_df['Vendor number']=np.nan
  
else:
  for i in tqdm(range(len(input_df))):
    vendorFlag(i)

6

  0%|          | 0/497 [00:00<?, ?it/s]

In [88]:
input_df.Vendor_Flag.unique()

array(['Old', 'New'], dtype=object)

In [89]:
input_df.shape[0]

497

In [90]:
#stop

In [91]:
input_df['Vendor name'].nunique()

497

In [92]:
input_df.replace(" ", np.nan, inplace=True)

In [93]:
input_df.shape[0]

497

In [94]:
inp_df_shape1 = input_df.shape[0]
inp_df_shape1

497

In [170]:
input_df['Vendor_name_Initials'].isna().sum()

0

In [171]:
if input_df['Vendor_name_Initials'].isna().sum() > 0:
  input_df_null_Vn_initial_records = input_df[input_df['Vendor_name_Initials'].isnull()]
  input_df_null_Vn_initial_records.to_excel('input df null Vn initials.xlsx',index=False,encoding='utf8')
  files.download('input df null Vn initials.xlsx')
  input_df.dropna(subset = ["Vendor_name_Initials"],inplace=True) 
  
input_df.shape[0] # also add a condition if any NULLs are present in the initials. And take the count for the final info
# this code can also be alter where one choose to have the filtered input data

497

In [99]:
# dropping NA again IF there is any while creating Vendor_name_Initials else it will be zero
no_of_null_inp_records2 = inp_df_shape1 - input_df.shape[0]
no_of_null_inp_records2

0

In [100]:
input_df.shape

(497, 10)

In [101]:
input_df['Vendor name'].isna().sum()

0

In [102]:
input_df.reset_index(inplace=True,drop=True)

In [103]:
#input_df[input_df['Clean_Vendor_Name'] == input_df['Clean_Vendor_Name'].iloc[276]]

In [104]:
input_df.shape[0]

497

In [105]:
n= input_df.Vendor_Flag.nunique()
print(n)

2

In [106]:
def unique_vendor_flag(n):
  if n==2:
    x,y = input_df.Vendor_Flag.unique()
    return(x,y)
  else:
    return(input_df.Vendor_Flag.unique())

In [107]:
new_records_with_dup = input_df[input_df.Vendor_Flag =='New'].shape[0] #Duplicate vendor names
new_records_with_dup

68

In [108]:
old_records_with_dup = input_df[input_df.Vendor_Flag =='Old'].shape[0] #Duplicate vendor names
old_records_with_dup

429

In [109]:
inp_new_flag_df = input_df[input_df.Vendor_Flag =='New']
inp_new_flag_df.reset_index(drop=True,inplace=True)
inp_new_flag_df.head(5)

     DataSource Vendor number  ...     crisp_vendor_name  Vendor_Flag
0  SAP SHP (S4)    1000197416  ...  protolabsgermanygmbh          New
1         Ariba  30118181-A10  ...                  pepi          New
2  SAP SHP (S4)    1000071837  ...     adeccotrainingsrl          New
3  SAP SHP (S4)    1000071598  ...    bccentroassistenza          New
4          XPPS         36130  ...     gehrckensgmbhcokg          New

[5 rows x 10 columns]

In [110]:
new_records = inp_new_flag_df['Vendor name'].count()
new_record_non_dup = inp_new_flag_df['Vendor name'].nunique()
print(new_records,new_record_non_dup)

68 68

In [111]:
inp_old_flag_df = input_df[input_df.Vendor_Flag == 'Old']
inp_old_flag_df.reset_index(drop=True,inplace=True)
inp_old_flag_df.shape[0]

429

In [112]:
old_records = inp_old_flag_df['Vendor name'].count()
old_records_non_dup = inp_old_flag_df['Vendor name'].nunique()
print(old_records,old_records_non_dup)

429 429

In [113]:
inp_old_flag_df.head()

           DataSource Vendor number  ...       crisp_vendor_name  Vendor_Flag
0               Ariba    1031587-A9  ...                 gartner          Old
1             JDE CAM        176488  ...          federalexpress          Old
2  3rd Party Security        750010  ...  hamosadlebetichutgahut          Old
3                 IFS    FI20244977  ...                idescooy          Old
4        SAP SHP (S4)    1000073115  ...                euracier          Old

[5 rows x 10 columns]

In [114]:
merged_inp_old_flag_df = pd.merge(inp_old_flag_df, clean_main_df['Clean_Vendor_Name'], on=['Clean_Vendor_Name'], how='inner')
##merged_inp_old_flag_df.dropna(subset=['Clean_Vendor_Name','Vendor_name_Initials'],inplace=True)
merged_inp_old_flag_df.drop_duplicates(subset=['Vendor name'],inplace=True)
merged_inp_old_flag_df.reset_index(drop=True,inplace=True)

In [115]:
merged_inp_old_flag_df.head()

           DataSource Vendor number  ...       crisp_vendor_name  Vendor_Flag
0               Ariba    1031587-A9  ...                 gartner          Old
1             JDE CAM        176488  ...          federalexpress          Old
2  3rd Party Security        750010  ...  hamosadlebetichutgahut          Old
3                 IFS    FI20244977  ...                idescooy          Old
4        SAP SHP (S4)    1000073115  ...                euracier          Old

[5 rows x 10 columns]

In [116]:

merged_inp_old_flag_df.reset_index(drop=True,inplace=True)

if merged_inp_old_flag_df[merged_inp_old_flag_df.duplicated(subset='Vendor name')].shape[0]>0:
  merged_inp_old_flag_df[merged_inp_old_flag_df.drop_duplicates(subset='Vendor name')]


merged_inp_old_flag_df_VN_list = merged_inp_old_flag_df['Clean_Vendor_Name'].tolist()

In [117]:
#to take out tthe unfit data
inp_old_flag_df_unfit= inp_old_flag_df[~inp_old_flag_df['Clean_Vendor_Name'].isin(merged_inp_old_flag_df_VN_list)]
inp_old_flag_df_unfit[inp_old_flag_df_unfit.duplicated(subset='Vendor name')].shape[0]
inp_old_flag_df_unfit.to_excel(f'Input_old_unfit_data.xlsx',index=False,encoding='utf8')
files.download('Input_old_unfit_data.xlsx')

In [118]:
inp_old_flag_df_unfit.shape[0]

0

In [119]:
#no_of_fit_old_records
no_of_fit_old_records = merged_inp_old_flag_df.shape[0]

In [120]:
input_df.shape[0]

497

In [121]:
tot_no_of_null_inp_records = no_of_null_inp_records1 + no_of_null_inp_records2 
tot_no_of_null_inp_records

0

In [122]:
no_of_unfit_old_records = inp_old_flag_df.shape[0] - no_of_fit_old_records
#no_of_unfit_old_records

In [123]:
tot_no_of_clean_inp_records = input_df.shape[0]# this contains duplicate Vendon names but combination of all columns are unique
tot_no_of_unique_vendors = input_df['Vendor name'].nunique()

In [124]:
#input_df = input_df.sample(100)
input_df.reset_index(drop=True,inplace=True)

In [125]:
#stop

In [126]:
#input_df['Vendor_Flag'].unique() == 'Old'

In [127]:
if n==2:
    inp_df_New, inp_df_Old = [x for _, x in input_df.groupby(input_df['Vendor_Flag'] == 'Old')]
    print(inp_df_Old['Vendor name'].nunique())

    inp_ini_list = np.sort(inp_df_Old.Vendor_name_Initials.unique())
    grp_input_df_new=[]
    
    # Cleaning chamber:
    inp_df_New_output=inp_CleaningChamber(inp_df_New) #added new line after this line # this is one of the Dataframe
    inp_df_New_output.drop(columns=['Vendor_name_Initials','Clean_Vendor_Name'],axis=1,inplace=True)
    inp_df_New_output['Vendor_Name_cleansed'] = inp_df_New_output['Vendor_Name_cleansed'].apply(lambda x: x.upper())
    # write a condition that if there is no values in datasource or vendor number then  replace the same with nan
    
    inp_df_New_output['Manual Harmonized']=np.nan
    inp_df_New_output['Match Ratio']=np.nan
    inp_df_New_output['True Match Flag']=np.nan
    inp_df_New_output['Match_word_len'] = np.nan
    
    inp_df_New_output= inp_df_New_output[['DataSource','Vendor number','Vendor name','Vendor_Name_cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']]
    
    inp_df_New_output.columns=['DataSource','Vendor number','Vendor name','Predicted Names/ Model Cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']

    inp_df_New_output.reset_index(drop=True,inplace=True)
    
    
    # Model chamber:
    inp_ini_list = inp_ini_list.tolist()
    grp_input_df = bucket_df(inp_df_Old,inp_ini_list)
    
    
    final_frame = []
    for i in tqdm(range(len(inp_ini_list))):
        for j in range(len(clean_ini_list)):
            if inp_ini_list[i]==clean_ini_list[j]:
                # we need to pass index ('j') to model defination. After this you can do global to name the DF's
                print('index value of clean_ini_list to be matched with inp_ini_list : ',j)
                print(inp_ini_list[i])
                print(clean_ini_list[j])                
                time_taken,grp_number,sgd_classifier=sgd_clf(j)
                print(f'[Info] Time taken to train group member "{grp_number}": {time_taken}')
                
                df_list = grp_input_df[i]['Clean_Vendor_Name'].values
                #print(df_list)
                frame=[]
                pred_st_time =  datetime.now()
                for k in tqdm(df_list):
                    predict_val = pd.DataFrame(sgd_classifier.predict(count_vect.transform([str(k)])))
                    frame.append(predict_val)
                inter_frame = pd.concat(frame).reset_index()
                inter_frame.drop('index',axis=1,inplace=True)
                frame_df_list= pd.DataFrame(df_list)
                row_val= pd.concat([frame_df_list, inter_frame], axis = 1) # try global here
                pred_end_time =  datetime.now()
                pred_time_taken = pred_end_time - pred_st_time
                pred_time_taken = time_util(pred_time_taken)
                print(f'[Info] Time taken to predict {grp_number}: {pred_time_taken}')
                print('-----------------------------------------------------------------------------------------------')
                final_frame.append(row_val)  
    final_output = pd.concat(final_frame)
    final_output.reset_index(inplace=True)
    final_output.drop('index',axis=1,inplace=True)
    final_output.columns=['Vendor_names','New_Supplier_Pred']
    final_output['New_Supplier_Pred'] = final_output['New_Supplier_Pred'].apply(lambda x: x.upper())
    final_output['New_Supplier_Pred'] = final_output['New_Supplier_Pred'].apply(lambda x: x.upper())
    clean_main_df.sort_values(by=['Clean_Vendor_Name'])
    
    merged_final = pd.merge(final_output,inp_df_Old,left_on='Vendor_names',right_on='Clean_Vendor_Name',how='left')
    merged_final.drop_duplicates(subset=['Vendor name'],inplace=True)
    merged_final.drop(columns=['Vendor_names','Vendor_name_Initials'],axis=1,inplace=True)
    merged_final = merged_final[['DataSource','Vendor number','Vendor name','New_Supplier_Pred','Clean_Vendor_Name','crisp_vendor_name','Vendor_Flag', 'Spend (USD)','Segment','Primary Category']]    
    merged_final =  pd.merge(merged_final,clean_main_df[['Clean_Vendor_Name','crisp_vendor_name','New Supplier']],left_on='crisp_vendor_name',right_on='crisp_vendor_name',how='left') # previously used 'Clean_Vendor_Name'
    merged_final.drop_duplicates(subset=['Vendor name'],inplace=True)
    #merged_final.drop(columns=['Clean_Vendor_Name','crisp_vendor_name'],axis=1,inplace=True)
    merged_final = merged_final[['DataSource','Vendor number','Vendor name','New_Supplier_Pred','New Supplier','Vendor_Flag','Spend (USD)','Segment','Primary Category']] 
    merged_final.columns=['DataSource','Vendor number','Vendor name','Model_pred_Supplier','Prev_Predicted_Supplier','Vendor_Flag','Spend (USD)','Segment','Primary Category']
    merged_final['Prev_Predicted_Supplier'] = merged_final['Prev_Predicted_Supplier'].apply(lambda x: x.upper())
    merged_final['Match_ratio']= merged_final.apply(lambda x: fuzz.ratio(str(x['Model_pred_Supplier']),str(x['Prev_Predicted_Supplier'])),axis=1)
    merged_final['Match_word_len'] = np.nan
    merged_final['True Match Flag']= ''
    merged_final.reset_index(drop=True,inplace=True)

    for i in tqdm(range(len(merged_final))):
        Match_wordLength(i)

    for i in tqdm(range(len(merged_final))):
      if (str(merged_final['Match_ratio'][i])=='100') & (merged_final['Match_word_len'][i] == 'Same Length'):
          merged_final['True Match Flag'].loc[i]= 'Yes'
      else:
          merged_final['True Match Flag'].loc[i]= 'No'

    merged_final.columns=['DataSource','Vendor number','Vendor name','Predicted Names/ Model Cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']
    merged_final['DataSource']=merged_final['DataSource'].apply(ds_cleansing)
    
    merged_final= final_output_sup_name_Cleaning(merged_final,'Predicted Names/ Model Cleansed')
    merged_final= final_output_sup_name_Cleaning(merged_final,'Manual Harmonized')


elif(n==1 and (input_df['Vendor_Flag'].unique() == 'New')):
  # put logic when the output is needed for only OLD records and n==1 
  # write a elif condition that if n==1 and only New records are there then
    print('Elif section is running for NEW...')
    print(input_df['Vendor name'].nunique())

    inp_ini_list = np.sort(input_df.Vendor_name_Initials.unique())
        
    # Cleaning chamber:
    inp_df_New_output=inp_CleaningChamber(input_df) #added new line after this line # this is one of the Dataframe
    inp_df_New_output.drop(columns=['Vendor_name_Initials','Clean_Vendor_Name'],axis=1,inplace=True)
    inp_df_New_output['Vendor_Name_cleansed'] = inp_df_New_output['Vendor_Name_cleansed'].apply(lambda x: x.upper())
    # write a condition that if there is no values in datasource or vendor number then  replace the same with nan
    
    inp_df_New_output['Manual Harmonized']=np.nan
    inp_df_New_output['Match Ratio']=np.nan
    inp_df_New_output['True Match Flag']=np.nan
    inp_df_New_output['Match_word_len'] = np.nan
    
    inp_df_New_output= inp_df_New_output[['DataSource','Vendor number','Vendor name','Vendor_Name_cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']]
    
    inp_df_New_output.columns=['DataSource','Vendor number','Vendor name','Predicted Names/ Model Cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']

    inp_df_New_output.reset_index(drop=True,inplace=True)
    
elif(n==1 and (input_df['Vendor_Flag'].unique() == 'Old')):
  # put logic when the output is needed for only OLD records and n==1 
  # write a elif condition that if n==1 and only New records are there then
  print('Elif section is running  for Old records...')
  print(input_df['Vendor name'].nunique())

  inp_ini_list = np.sort(input_df.Vendor_name_Initials.unique())  
  # Model chamber:
  inp_ini_list = inp_ini_list.tolist()
  grp_input_df = bucket_df(input_df,inp_ini_list)
  
  final_frame = []
  for i in tqdm(range(len(inp_ini_list))):
      for j in range(len(clean_ini_list)):
          if inp_ini_list[i]==clean_ini_list[j]:
              # we need to pass index ('j') to model defination. After this you can do global to name the DF's
              print('index value of clean_ini_list to be matched with inp_ini_list : ',j)
              print(inp_ini_list[i])
              print(clean_ini_list[j])                
              time_taken,grp_number,sgd_classifier=sgd_clf(j)
              print(f'[Info] Time taken to train group member "{grp_number}": {time_taken}')
              
              df_list = grp_input_df[i]['Clean_Vendor_Name'].values
              #print(df_list)
              frame=[]
              pred_st_time =  datetime.now()
              for k in tqdm(df_list):
                  predict_val = pd.DataFrame(sgd_classifier.predict(count_vect.transform([str(k)])))
                  frame.append(predict_val)
              inter_frame = pd.concat(frame).reset_index()
              inter_frame.drop('index',axis=1,inplace=True)
              frame_df_list= pd.DataFrame(df_list)
              row_val= pd.concat([frame_df_list, inter_frame], axis = 1) # try global here
              pred_end_time =  datetime.now()
              pred_time_taken = pred_end_time - pred_st_time
              pred_time_taken = time_util(pred_time_taken)
              print(f'[Info] Time taken to predict {grp_number}: {pred_time_taken}')
              print('-----------------------------------------------------------------------------------------------')
              final_frame.append(row_val)  
  final_output = pd.concat(final_frame)
  final_output.reset_index(inplace=True)
  final_output.drop('index',axis=1,inplace=True)
  final_output.columns=['Vendor_names','New_Supplier_Pred']
  final_output['New_Supplier_Pred'] = final_output['New_Supplier_Pred'].apply(lambda x: x.upper())
  final_output['New_Supplier_Pred'] = final_output['New_Supplier_Pred'].apply(lambda x: x.upper())
  clean_main_df.sort_values(by=['Clean_Vendor_Name'])
  
  merged_final = pd.merge(final_output,inp_df_Old,left_on='Vendor_names',right_on='Clean_Vendor_Name',how='left')
  merged_final.drop_duplicates(subset=['Vendor name'],inplace=True)
  merged_final.drop(columns=['Vendor_names','Vendor_name_Initials'],axis=1,inplace=True)
  merged_final = merged_final[['DataSource','Vendor number','Vendor name','New_Supplier_Pred','Clean_Vendor_Name','crisp_vendor_name','Vendor_Flag', 'Spend (USD)','Segment','Primary Category']]    
  merged_final =  pd.merge(merged_final,clean_main_df[['Clean_Vendor_Name','crisp_vendor_name','New Supplier']],left_on='crisp_vendor_name',right_on='crisp_vendor_name',how='left') # previously used 'Clean_Vendor_Name'
  merged_final.drop_duplicates(subset=['Vendor name'],inplace=True)
  #merged_final.drop(columns=['Clean_Vendor_Name','crisp_vendor_name'],axis=1,inplace=True)
  merged_final = merged_final[['DataSource','Vendor number','Vendor name','New_Supplier_Pred','New Supplier','Vendor_Flag','Spend (USD)','Segment','Primary Category']] 
  merged_final.columns=['DataSource','Vendor number','Vendor name','Model_pred_Supplier','Prev_Predicted_Supplier','Vendor_Flag','Spend (USD)','Segment','Primary Category']
  merged_final['Prev_Predicted_Supplier'] = merged_final['Prev_Predicted_Supplier'].apply(lambda x: x.upper())
  merged_final['Match_ratio']= merged_final.apply(lambda x: fuzz.ratio(str(x['Model_pred_Supplier']),str(x['Prev_Predicted_Supplier'])),axis=1)
  merged_final['Match_word_len'] = np.nan
  merged_final['True Match Flag']= ''
  merged_final.reset_index(drop=True,inplace=True)

  for i in tqdm(range(len(merged_final))):
      Match_wordLength(i)

  for i in tqdm(range(len(merged_final))):
    if (str(merged_final['Match_ratio'][i])=='100') & (merged_final['Match_word_len'][i] == 'Same Length'):
        merged_final['True Match Flag'].loc[i]= 'Yes'
    else:
        merged_final['True Match Flag'].loc[i]= 'No'

  merged_final.columns=['DataSource','Vendor number','Vendor name','Predicted Names/ Model Cleansed','Manual Harmonized','Vendor_Flag','Spend (USD)','Segment','Primary Category','Match Ratio','Match_word_len','True Match Flag']
  merged_final['DataSource']=merged_final['DataSource'].apply(ds_cleansing)
  merged_final= final_output_sup_name_Cleaning(merged_final,'Predicted Names/ Model Cleansed')
  merged_final= final_output_sup_name_Cleaning(merged_final,'Manual Harmonized')

429

  0%|          | 0/28 [00:00<?, ?it/s]

index value of clean_ini_list to be matched with inp_ini_list :  3
3
3
[Info] Time taken to train group member "3": 00 00 secs

  0%|          | 0/1 [00:00<?, ?it/s]

[Info] Time taken to predict 3: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  5
5
5
[Info] Time taken to train group member "5": 00 00 secs

  0%|          | 0/1 [00:00<?, ?it/s]

[Info] Time taken to predict 5: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  10
a
a
[Info] Time taken to train group member "a": 1 min & 12 secs

  0%|          | 0/42 [00:00<?, ?it/s]

[Info] Time taken to predict a: 00 46 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  11
b
b
[Info] Time taken to train group member "b": 00 22 secs

  0%|          | 0/29 [00:00<?, ?it/s]

[Info] Time taken to predict b: 00 10 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  12
c
c
[Info] Time taken to train group member "c": 1 min & 2 secs

  0%|          | 0/31 [00:00<?, ?it/s]

[Info] Time taken to predict c: 00 29 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  13
d
d
[Info] Time taken to train group member "d": 00 20 secs

  0%|          | 0/20 [00:00<?, ?it/s]

[Info] Time taken to predict d: 00 06 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  14
e
e
[Info] Time taken to train group member "e": 00 18 secs

  0%|          | 0/15 [00:00<?, ?it/s]

[Info] Time taken to predict e: 00 04 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  15
f
f
[Info] Time taken to train group member "f": 00 10 secs

  0%|          | 0/21 [00:00<?, ?it/s]

[Info] Time taken to predict f: 00 03 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  16
g
g
[Info] Time taken to train group member "g": 00 12 secs

  0%|          | 0/14 [00:00<?, ?it/s]

[Info] Time taken to predict g: 00 02 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  17
h
h
[Info] Time taken to train group member "h": 00 14 secs

  0%|          | 0/16 [00:00<?, ?it/s]

[Info] Time taken to predict h: 00 02 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  18
i
i
[Info] Time taken to train group member "i": 00 09 secs

  0%|          | 0/14 [00:00<?, ?it/s]

[Info] Time taken to predict i: 00 01 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  19
j
j
[Info] Time taken to train group member "j": 00 11 secs

  0%|          | 0/10 [00:00<?, ?it/s]

[Info] Time taken to predict j: 00 01 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  20
k
k
[Info] Time taken to train group member "k": 00 07 secs

  0%|          | 0/13 [00:00<?, ?it/s]

[Info] Time taken to predict k: 00 01 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  21
l
l
[Info] Time taken to train group member "l": 00 13 secs

  0%|          | 0/13 [00:00<?, ?it/s]

[Info] Time taken to predict l: 00 02 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  22
m
m
[Info] Time taken to train group member "m": 00 42 secs

  0%|          | 0/23 [00:00<?, ?it/s]

[Info] Time taken to predict m: 00 11 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  23
n
n
[Info] Time taken to train group member "n": 00 09 secs

  0%|          | 0/12 [00:00<?, ?it/s]

[Info] Time taken to predict n: 00 01 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  24
o
o
[Info] Time taken to train group member "o": 00 02 secs

  0%|          | 0/4 [00:00<?, ?it/s]

[Info] Time taken to predict o: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  25
p
p
[Info] Time taken to train group member "p": 00 27 secs

  0%|          | 0/21 [00:00<?, ?it/s]

[Info] Time taken to predict p: 00 07 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  26
q
q
[Info] Time taken to train group member "q": 00 00 secs

  0%|          | 0/2 [00:00<?, ?it/s]

[Info] Time taken to predict q: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  27
r
r
[Info] Time taken to train group member "r": 00 16 secs

  0%|          | 0/17 [00:00<?, ?it/s]

[Info] Time taken to predict r: 00 03 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  28
s
s
[Info] Time taken to train group member "s": 3 mins & 10 secs

  0%|          | 0/41 [00:00<?, ?it/s]

[Info] Time taken to predict s: 00 39 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  29
t
t
[Info] Time taken to train group member "t": 00 36 secs

  0%|          | 0/24 [00:00<?, ?it/s]

[Info] Time taken to predict t: 00 08 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  30
u
u
[Info] Time taken to train group member "u": 00 01 secs

  0%|          | 0/5 [00:00<?, ?it/s]

[Info] Time taken to predict u: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  31
v
v
[Info] Time taken to train group member "v": 00 03 secs

  0%|          | 0/10 [00:00<?, ?it/s]

[Info] Time taken to predict v: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  32
w
w
[Info] Time taken to train group member "w": 00 07 secs

  0%|          | 0/15 [00:00<?, ?it/s]

[Info] Time taken to predict w: 00 01 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  33
x
x
[Info] Time taken to train group member "x": 00 00 secs

  0%|          | 0/5 [00:00<?, ?it/s]

[Info] Time taken to predict x: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  34
y
y
[Info] Time taken to train group member "y": 00 01 secs

  0%|          | 0/7 [00:00<?, ?it/s]

[Info] Time taken to predict y: 00 00 secs
-----------------------------------------------------------------------------------------------
index value of clean_ini_list to be matched with inp_ini_list :  35
z
z
[Info] Time taken to train group member "z": 00 00 secs

  0%|          | 0/3 [00:00<?, ?it/s]

[Info] Time taken to predict z: 00 00 secs
-----------------------------------------------------------------------------------------------

  0%|          | 0/429 [00:00<?, ?it/s]

  0%|          | 0/429 [00:00<?, ?it/s]

In [128]:
#merged_final['DataSource']=merged_final['DataSource'].apply(ds_cleansing)
merged_final.head()

    DataSource      Vendor number  ... Match_word_len True Match Flag
0  OBIEE INDIA  SEFBV00002-INDIAC  ...    Same Length             Yes
1      SAP C11           30089116  ...    Same Length             Yes
2      SAP E03             125628  ...    Same Length             Yes
3      SAP E03             112463  ...    Same Length             Yes
4      SAP P10            1097485  ...    Same Length             Yes

[5 rows x 12 columns]

In [129]:
no_of_dup_merged_records = merged_final[merged_final.duplicated(subset=['Vendor name'])].shape[0] # this will give duplicates if any gets generated
non_dup_merged_records = merged_final.shape[0] - no_of_dup_merged_records
print(f"No of duplicate records: {no_of_dup_merged_records} \nNo of Non duplicate records: {non_dup_merged_records}") #it is good to have "No of duplicate records:" as "0"

No of duplicate records: 0
No of Non duplicate records: 429

In [130]:
if no_of_dup_merged_records>0:
  merged_final.drop_duplicates(subset=['Vendor name'],inplace=True) # Put if condition when no_of_dup_merged_records> 0, then do the drop

In [131]:
predict_df_len = merged_final.shape[0]
predict_df_len

429

In [132]:
# drop Nan from vendor names
count_na_merged_final = merged_final.isnull().sum().max()
print("Predicted Dataframe NA Count: ",count_na_merged_final)
if count_na_merged_final>0:
  na_dict  = merged_final.isnull().sum().to_dict()#:  #.max()>0
  for k,v in na_dict.items():
    if v>0:
      if (v == merged_final.isnull().sum().max()) and (k in ['DataSource',	'Vendor number',	'Vendor name']):
        print("The column with maximum NA counts: ",k)
        print("Info:   Dropping the NAs from the Dataframe:::::::::::")
        merged_final.dropna(inplace=True)
        merged_final.reset_index(inplace=True,drop=True)

#merged_final.dropna(subset = ["Vendor name"],inplace=True)  # here also put condition for NA then do Na and take the count as well

merged_final.sort_values("Spend (USD)", ascending=False,inplace=True)
merged_final.reset_index(drop=True,inplace=True)
validation_file = merged_final.copy()
validation_file.sort_values("Predicted Names/ Model Cleansed", ascending=True,inplace=True)
validation_file = validation_file[['Predicted Names/ Model Cleansed', 'Manual Harmonized', 'Vendor_Flag','DataSource', 'Vendor number', 'Vendor name','Spend (USD)','Segment','Primary Category', 'Match Ratio', 'True Match Flag']]
validation_file.reset_index(drop=True,inplace=True)

Predicted Dataframe NA Count:  0

In [133]:
inp_df_New_output.shape

(68, 12)

494

In [135]:
merged_validation_file  = pd.concat([validation_file, inp_df_New_output])
merged_validation_file.sort_values("Spend (USD)", ascending=False,inplace=True)
merged_validation_file.reset_index(inplace=True,drop=True)
non_match_final_validation = merged_validation_file.copy()
non_match_final_validation = non_match_final_validation[(non_match_final_validation['Match Ratio']<90.00)]#(non_match_final_validation['True Match Flag'] == 'No')] # include less than 90%
count_non_match_final_validation = non_match_final_validation.shape[0]

final_validation_file = merged_validation_file.copy()
final_validation_file = final_validation_file[(final_validation_file['True Match Flag'] != 'No') | (final_validation_file['Match Ratio']>=90.00) | (final_validation_file['True Match Flag'] == 'Yes')] # 90% include
print(final_validation_file.shape[0],count_non_match_final_validation)

483 14

494

In [137]:
merged_validation_file['Spend (USD)']=merged_validation_file['Spend (USD)'].astype(float)
merged_validation_file = merged_validation_file[(merged_validation_file['True Match Flag'] != 'No') | (merged_validation_file['Match Ratio']>=90.00)] # 90% include
merged_validation_file.reset_index(inplace=True,drop=True)
merged_validation_file['Spend (USD)']=merged_validation_file['Spend (USD)'].astype(float)
merged_validation_file = merged_validation_file.assign(totalSpend = merged_validation_file['Spend (USD)']).groupby('Predicted Names/ Model Cleansed').agg({'totalSpend':sum})
#merged_validation_file = merged_validation_file.assign(totalSpend = np.where(merged_validation_file['True Match Flag']!='No',merged_validation_file['Spend (USD)'],0)).groupby('Predicted Names/ Model Cleansed').agg({'totalSpend':sum})
merged_validation_file.sort_values("totalSpend", ascending=False,inplace=True)
merged_validation_file.reset_index(inplace=True)
merged_validation_file['totalSpend']=merged_validation_file['totalSpend'].astype(float)
merged_validation_file['Spend (USD)_cumulative'] = merged_validation_file['totalSpend'].cumsum()
merged_validation_file['Spend (USD)_cumulative']=merged_validation_file['Spend (USD)_cumulative'].astype(float)
merged_validation_file['totalSpend']=merged_validation_file['totalSpend'].astype(float)
merged_validation_file['Cumulative Rolling %'] = (merged_validation_file['Spend (USD)_cumulative']  / merged_validation_file['totalSpend'].sum())*100
merged_validation_file['Supplier %'] = (merged_validation_file['totalSpend']  / merged_validation_file['totalSpend'].sum())*100

merged_validation_file['Spend (USD)_cumulative'] = merged_validation_file['Spend (USD)_cumulative'].apply(lambda x: f'{x:.2f}')

merged_validation_file['Cumulative Rolling %'] = pd.to_numeric(merged_validation_file['Cumulative Rolling %'], downcast="float")
merged_validation_file['Cumulative Rolling %'] = merged_validation_file['Cumulative Rolling %'].apply(lambda x: f'{x:.2f}')

merged_validation_file['Supplier %'] = pd.to_numeric(merged_validation_file['Supplier %'], downcast="float")
merged_validation_file['Supplier %'] = merged_validation_file['Supplier %'].apply(lambda x: f'{x:.2f}')
merged_validation_file.reset_index(drop=True,inplace=True)


merged_validation_file['Group'] = ''
merged_validation_file['Cumulative Rolling %'] = pd.to_numeric(merged_validation_file['Cumulative Rolling %'], downcast="float")
merged_validation_file.loc[merged_validation_file['Cumulative Rolling %']<=80.0, ['Group']] = 1
merged_validation_file.loc[merged_validation_file['Cumulative Rolling %']>80.0, ['Group']] = 2
merged_validation_file.loc[merged_validation_file['Cumulative Rolling %']>90, ['Group']] = 3
merged_validation_file.loc[merged_validation_file['Cumulative Rolling %']>95, ['Group']] = 4
merged_validation_file.loc[merged_validation_file['Cumulative Rolling %']>98, ['Group']] = 5

merged_validation_file['Cumulative Rolling %'] = merged_validation_file['Cumulative Rolling %'].apply(lambda x: f'{float(x):.2f}')
merged_validation_file['totalSpend'] = merged_validation_file['totalSpend'].apply(lambda x: f'{float(x):.2f}')

In [138]:
merged_validation_file

             Predicted Names/ Model Cleansed   totalSpend  ... Supplier % Group
0               DEFOND ELECTRICAL INDUSTRIES  86442962.20  ...      50.10     1
1                         PHIHONG TECHNOLOGY  14252981.29  ...       8.26     1
2                       KINGS YAO INDUSTRIAL   8726282.11  ...       5.06     1
3                               WINTEK TOOLS   5897724.65  ...       3.42     1
4                                     ORACLE   5833694.67  ...       3.38     1
..                                       ...          ...  ...        ...   ...
474                          DRUKWERKDEAL.NL     -2207.37  ...      -0.00     5
475                          CONTESSA DANILO     -3051.13  ...      -0.00     5
476                                   124750     -3215.81  ...      -0.00     5
477               LUSAVOUGA-MAQ.ACES.IND.LDA    -12723.29  ...      -0.01     5
478  E & H INDUSTRIES LLC/DBA E DISTRIBUTION   -386293.31  ...      -0.22     5

[479 rows x 6 columns]

In [139]:
final_validation_file =  pd.merge(final_validation_file,merged_validation_file[['Predicted Names/ Model Cleansed','totalSpend','Supplier %','Spend (USD)_cumulative','Cumulative Rolling %','Group']],left_on='Predicted Names/ Model Cleansed',right_on='Predicted Names/ Model Cleansed',how='left')
final_validation_file.sort_values("Predicted Names/ Model Cleansed", ascending=True,inplace=True)
final_validation_file.drop(columns=['Match Ratio', 'True Match Flag',	'Match_word_len'],inplace=True)
final_validation_file['Spend (USD)'] = final_validation_file['Spend (USD)'].apply(lambda x: f'{x:.2f}')
final_validation_file = final_validation_file[['Predicted Names/ Model Cleansed', 'Manual Harmonized', 'Vendor_Flag',\
                                        'DataSource', 'Vendor number', 'Vendor name', 'Spend (USD)',\
                                        'totalSpend','Supplier %','Spend (USD)_cumulative', 'Cumulative Rolling %',\
                                        'Group','Segment','Primary Category']]
final_validation_file.reset_index(drop=True,inplace=True)

In [140]:
final_validation_file.tail(5)

          Predicted Names/ Model Cleansed  ...      Primary Category
478                    YUCHENG ENTERPRISE  ...  Purchased Components
479                YUE JIE METAL INDUSTRY  ...  Purchased Components
480          YUSHENG INSTRUMENT CO., LTD.  ...   General Procurement
481  ZHENGYE MACHINERY SHANGHAI CO., LTD.  ...   General Procurement
482                      ZICATOR SA DE CV  ...           Commodities

[5 rows x 14 columns]

In [141]:
final_validation_records = final_validation_file.shape[0]
final_validation_records

483

In [142]:
#((326911619.44+85615877.26+206579069.43)/1806555966.77)*100

In [143]:
model_chamber_records = merged_final.shape[0]
model_chamber_records

429

In [144]:
cleansed_records = inp_df_New_output.shape[0]
cleansed_records

68

# Accuracy:

In [145]:
true_matched_records = merged_final[merged_final['True Match Flag'] == 'Yes'].shape[0]
true_matched_records

405

In [146]:
model_accuracy = (true_matched_records/model_chamber_records)*100
model_accuracy

94.4055944055944

In [147]:
date = datetime.now().strftime("%Y_%b_%d")

In [148]:
final_validation_file.to_excel('Validation.xlsx',index=False,encoding='utf8')
files.download('Validation.xlsx')

In [149]:
# Send the ouput prredicted file to ouput folder
#merged_final.to_excel(f'C:/Users/PXC0909/OneDrive - Stanley Black & Decker/Desktop/SBD/Vendor Harmonization/VH_Data/Predicted/merged_final_{date}.xlsx',index=False,encoding='utf_8_sig')
merged_final.to_excel('Prediction.xlsx',index=False,encoding='utf8')
files.download('Prediction.xlsx')

In [150]:
# Send the new/ Ambiguous vendor output file to conformation folder
#inp_df_New_output.to_excel(f'C:/Users/PXC0909/OneDrive - Stanley Black & Decker/Desktop/SBD/Vendor Harmonization/VH_Data/Cleansed/Cleansed_Vendors_{date}.xlsx',index=False,encoding='utf_8_sig')
inp_df_New_output.to_excel(f'Cleansed_Vendors.xlsx',index=False,encoding='utf8')
files.download('Cleansed_Vendors.xlsx')

In [151]:
#inp_df_New_output.head()

In [152]:
merged_final.shape

(429, 12)

In [153]:
process_end_time =  datetime.now()

In [154]:
process_time_taken = process_end_time - process_start_time
process_time_taken = time_util(process_time_taken)

In [155]:
print(f'Time taken to execute complete script: {process_time_taken}')

Time taken to execute complete script: 26 mins & 13 secs

In [156]:
#mytext = 'The program is executed' #+str(process_time_taken)
#language = 'en'
#myobj = gTTS(text=mytext, lang=language, slow=False)
#myobj.save("time_taken.mp3")
#os.system("time_taken.mp3")

In [157]:
# Code to get the full information on data

# Information of Raw master data:::
# No of master files used:
print('No of master files/ file used: ',no_of_files)

# Total no of records in master data (including all type of records)
print("Total no of records: ", length)

# Total no of null records (repeatative cleaning)
tot_no_of_null_records = no_of_null_records1 + no_of_null_records2 + no_of_null_records3 
print("Total no of Null records: ",tot_no_of_null_records)

# No of bad/uncleaned master data:
print(f"No of bad/filtered/uncleaned master data: ", no_of_noise_flags)

# Total no of dropped records
no_of_dropped_records = tot_no_of_null_records + no_of_noise_flags
print("Total no of records removed: ",no_of_dropped_records)

# Total no of clean records:
no_of_clean_records =  length - no_of_dropped_records
print("No of Clean records:", no_of_clean_records)

# Total no of unique bad/uncleaned:
tot_no_of_unique_dirty_records = no_of_unique_dirty_records
print("No of (non-duplicate) records to clean: ", tot_no_of_unique_dirty_records)

# Total no of master records in use
print("No of records used as Master data: ", tot_no_of_clean_records)

# Percentage of unique bad/uncleaned records
print("Percentage of Foreign/ Dirty records: ", per_irr)

No of master files/ file used:  1
Total no of records:  228989
Total no of Null records:  105
No of bad/filtered/uncleaned master data:  0
Total no of records removed:  105
No of Clean records: 228884
No of (non-duplicate) records to clean:  0
No of records used as Master data:  228884
Percentage of Foreign/ Dirty records:  0.000

In [158]:
# Information of Input data:::
# No of Input files used
print('No of input files used: ', tot_files)
tot_files

# Total no of records in input data (including all type of records)
print('No of records in input data: ', no_of_raw_inp_records)

# Unique Flags:
print("Unique Flags are: ",unique_vendor_flag(n))

# No of Null records
tot_no_of_null_inp_records = no_of_null_inp_records1 + no_of_null_inp_records2 
print('Total no of null records to drop: ', tot_no_of_null_inp_records)

# Foreign counts:
if foreign_count>0:
  print('No of foreign records: ',foreign_count)

# No of new records:
no_of_new_records = new_records
print('No of "New" records: ',no_of_new_records)


# No of old records:
no_of_old_records = old_records
print('No of "Old" records: ',no_of_old_records)

# No of fit old records:
no_of_fit_old_records
#print('No of fit old records: ', no_of_fit_old_records)

# No of unfit old records:
no_of_unfit_old_records
#print('No of unfit old records: ', no_of_unfit_old_records)

# total no of clean input records
print('Total no of clean inp records: ',tot_no_of_clean_inp_records)

# total no of Unique vendors
print('Total no of Unique vendors: ',tot_no_of_unique_vendors)


# After Run:
# Total no of records as output from Model chamber:
print("No of records predicted: ", model_chamber_records)

# Total no of records as output from cleansing chamber:
print("No of records cleansed: ", cleansed_records)

# For Validaton file:
print("No of records in Validation file: ", final_validation_records)
print("No of records not used in Validation file: ", count_non_match_final_validation)

# Model Accuracy:
print("Model accuracy: ",model_accuracy)

No of input files used:  1
No of records in input data:  500
Unique Flags are:  ('Old', 'New')
Total no of null records to drop:  0
No of foreign records:  3
No of "New" records:  68
No of "Old" records:  429
Total no of clean inp records:  497
Total no of Unique vendors:  497
No of records predicted:  429
No of records cleansed:  68
No of records in Validation file:  483
No of records not used in Validation file:  14
Model accuracy:  94.4055944055944

# End of Script

# Below snippets are for testing purpose only

In [ ]:
import unicodedata
vn = "ł"
def norm_vendorNames1(vname):
  normalized = unicodedata.normalize('NFD', vname)
  norm_vname = u"".join([c for c in normalized if not unicodedata.combining(c)])
  norm_vname = trans_name(norm_vname)
  return(norm_vname)

print(norm_vendorNames1(vn))

In [ ]:
danish_text_raw = 'ø' # here you would load your text
print(danish_text_raw) # returns string
danish_text = danish_text_raw.encode('utf-8').decode() 
print(danish_text)

In [161]:
def to_unicode(in_string):
  if isinstance(in_string,str):
    out_string = in_string.encode().decode('utf-8')
  elif isinstance(in_string,unicode):
    out_string = in_string
  else:
    raise TypeError('not stringy')
  return out_string

In [162]:
to_unicode(danish_text_raw)

'ø'

In [163]:
import unicodedata as ud

def rmdiacritics(name):
    '''
    Return the base character of char, by "removing" any
    diacritics like accents or curls and strokes and the like.
    '''
    char_list = []
    for char in name:
      desc = ud.name(char)
      #print(desc)
      cutoff = desc.find(' WITH ')
      #print(cutoff)
      if cutoff == -1:
        char_list.append(char)
      elif cutoff != -1:
        desc = desc[:cutoff]
        #print(desc)
        try:
          char = ud.lookup(desc)
          #print(char)
          char_list.append(char)
        except KeyError:
            pass  # removing "WITH ..." produced an invalid name
    
    return ''.join(char_list)

In [164]:
rmdiacritics('BYMILJØETATEN')

'BYMILJOETATEN'

In [165]:
!pip install unidecode
from unidecode import unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.7/dist-packages (1.3.3)

In [166]:
from unidecode import unidecode
text = "E & Y K÷NYVVIZSGßLO KFT."
print(unidecode(text))

E & Y K/NYVVIZSGssLO KFT.

In [167]:
def decode_vnames(vname):
  return(unidecode(vname))

In [168]:
decode_vnames(s)

NameError: ignored

In [ ]:
decode_vnames('永恒力合力工业车辆租赁（上海）有限公司')

In [ ]:
'THEO’S PRESTIGE PAINT & PANE'

In [ ]:
s = 'Andr\xE9'

In [ ]:
s.encode().decode('utf-8', 'replace')

In [ ]:
u = s.encode('latin-1','replace').decode('ascii','replace')#.encode('utf-8', 'replace')#.decode('ascii','replace')
f= u.encode(encoding='utf-8', errors='strict')
u

In [ ]:
d = u.encode('utf-8','replace').decode('utf-8','replace')
d

In [ ]:
g = bytes(s, 'utf-8')
g= g.decode('ascii','replace')
g

In [ ]:
type(f),f

In [ ]:
h = f.decode('utf-8','replace').encode().decode('utf-8','replace')

In [ ]:
h.encode().decode('utf-8', 'replace')